name: Lint and run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  lint-and-run-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov plotly coverage-badge
          pip install .
          python -c "import widgets"

      - name: Run lint
        run: |
          flake8 src

      - name: Run Tests
        run: |
          pytest --cov-report term-missing --cov=widgets
          coverage-badge -o badge.svg